name: FirefoxWASMiOS
options:
  bundleIdPrefix: com.axoledstudent
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
targets:
  FirefoxWASMiOS:
    type: application
    platform: iOS
    sources:
      - path: FirefoxWASMiOS
    info:
      path: FirefoxWASMiOS/Info.plist
      properties:
        CFBundleDevelopmentRegion: zh_TW
        CFBundleDisplayName: Firefox WASM
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleLocalizations:
          - zh-Hant
          - en
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: FirefoxWASMiOS/FirefoxWASMiOS.entitlements
      properties:
        get-task-allow: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.axoledstudent.firefoxwasm
        PRODUCT_NAME: FirefoxWASM
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
schemes:
  FirefoxWASMiOS:
    build:
      targets:
        FirefoxWASMiOS: all
    run:
      config: Debug
    archive:
      config: Release
